### ISSUE TITLE
Live reload causing a full refresh instead of injecting CSS

### ISSUE THREAD

**Issue by iansinnott** [jenius/roots#594]
Hey everyone, am I missing something here? When using other workflows (e.g. Gulp) on other projects changes to stylus files don't cause a full browser refresh. The resulting CSS changes are injected into the browser, which is really fast. Is this not supported by Roots?

Currently using `3.0.0-rc.10`. Thanks.

**Comment by jenius** [comment]
This is not currently supported by roots. I played around with css injection in an earlier version of roots and it was inconsistent, often things would bug out and I'd have to manually refresh. For this reason I just kept it as a full refresh. Perhaps the tech has improved since then and it's more reliable. We're taking a look at [integrating browser-sync](https://github.com/jenius/roots/issues/367), which would solve this issue. If you're interesting in helping with this, that would be great.

For now I'm going to close this out as we can continue discussion in the browser-sync issue, but thanks for bringing it up!

**Comment by iansinnott** [comment]
Thanks Jeff, good to know. I will definitely keep an eye on this as so far it's the only thing I've found to not like about Roots.

**Comment by jenius** [comment]
Awesome, I'm glad you're liking everything else haha. There are a few thing we're working on and thinking about in the issues section that would improve roots anywhere from being marginally faster to orders of magnitude faster. Most of them are difficult issues, but we'll tackle them in time :grinning:
