### ISSUE TITLE
How to use write hook to change the output content?

### ISSUE THREAD

**Issue by ilife5** [jenius/roots#607]
I write compile_hooks like this:

```
  compile_hooks: ->
    write: write_hook.bind(@)

  write_hook = (ctx) ->
      path: path.join(ctx.roots.config.output_path(), ctx.file_options._path)
      content: "oooops"
```

But it`s not worked.

**Comment by jenius** [comment]
You need to make sure you also have `extract` set to true in the options so that the extension handles the file and removes it from roots' compile pipeline. Otherwise this should work fine. Here's an example of a tiny test extension that does a custom path and content rewrite which is part of roots' test suite:

https://github.com/jenius/roots/blob/master/test/fixtures/extensions/write_hook/app.coffee#L21-L30

Hope this helps! Feel free to drop by our [gitter chat](http://gitter.im/jenius/roots) if you have any quick questions about extension building. It definitely is complicated.

**Comment by ilife5** [comment]
@jenius 
Thank you, but it output nothing.

My code is here:

app.coffee

```
mdJade = require "markdown-jade"

module.exports =
  ignores: ['readme.md', '.idea/**', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf', 'template/**']

  extensions: [
    mdJade()
  ]

  open_browser: false

```
markdown-jade is my extension

```
path        = require "path"

module.exports = (opts) ->

  class MarkdownConversion
    constructor: (@roots) ->
      @category = "markdown"

    fs: ->
      extract: true
      detect: (f) ->
        path.extname(f.relative) is (".md")

    compile_hooks: ->
      write: (ctx) =>
        { path: path.join(ctx.roots.config.output_path(), "fff.html"), content: 'wow overrides' }
```

I use the code in the test suite and set extract true.

**Comment by jenius** [comment]
The code is tested in the link I just sent you and the test is passing, both on my local machine and on travis -- there is nothing broken on the roots side. You must have some error somewhere in your script. Are you sure the extension is running? Are you sure it's matching the correct files? Are you sure the output path is being generated correctly?

Spend a little time debugging this. Use `console.log` to figure out how your code is being run, and what is going where. Dig a little deeper :grinning:

**Comment by ilife5** [comment]
I think I get the point:)

I should use the <code>ctx.roots.root</code> get the root path, It transfrom 

root/fff.html ==> root/public/fff.html

When use <code>path.join(ctx.roots.config.output_path(), "fff.html")</code>

Although I get the target path root/public/fff.html, then 

```
//compile.coffee
obj.path = @roots.config.out(obj.path, obj.extension)
```
transform it to root/public/public/fff.html.

It is a little difficult to understand:)

Thanks a lot.
