### ISSUE TITLE
documentation/website improvements

### ISSUE THREAD

**Issue by tcurdt** [jenius/roots#660]
http://roots.cx/ is a nice web site - but boy! No link to the github repo?
And on http://roots.cx/articles/blogs not even a link to some example code?

**Comment by ganar** [comment]
I humbly suggest an article on how to update roots. I am on Version 3.1.0 and can't find the reference on how to update to 3.2.2

**Comment by declandewet** [comment]
@ganar since Roots is an npm module, you can update it just like any other npm module - `$ npm update roots -g`

@tcurdt I see your point - but this issue should really be taken up on the [roots.cx repo](https://github.com/carrot/roots-www), since the docs are a separate project to roots itself

Please post your feedback there

**Comment by jenius** [comment]
Agreed, thanks Declan!
