### ISSUE TITLE
How to properly import dependencies?

### ISSUE THREAD

**Issue by edravis** [jenius/roots#666]
I'm trying to understand the best pattern for using dependencies with roots. Both of Javascript and CSS ones.

With JS I'm currently using `browserify` and because CommonJS I just import the execution point (`app.js`) and then `browserify` load the dependencies as they are being required.

With CSS I'm currently using the default `stylus` with `css_pipeline`. And I'm not achieving a good importing. I used to work with `.sass` and I'm structuring the `assets/styles` the same way; and maybe this is wrong. I've the modules, partials and vendor files inside this directory and then a one starting point (`master.styl`) which just `@import` the files commented before. 

But then if I checked the `bundle.css` there's nothing. Looks like the `@import` isn't working. 
So, I've added these vendor files into the `files` array of `css_pipeline`. And it works, of course. But this means that the `master.styl` isn't doing nothing.

Also, I ran into another trouble that I don't get how to solve it. When I bundle both JS and CSS it makes me the bundle file and also the rest of files into the assets directory. I'll try to explain myself better. In `assets/scripts` I've `app.js` which starts all the JS execution and also `config.js`. After the roots compiling in the `public/` I get:
* `js/bundle.js`  -  the `app.js` and its proper development of dependecies
* `scripts/config.js`  -  the `config.js` itself 

I've tried to ignore these files. For example, ignoring `config.js` because I understand that it's being required inside the scope of `app.js`. But if do that then `app.js` it's unable to find it.
I've exactly the same trouble with CSS. If I don't ignore them then I've got the info twice. If I ignore'em then I cannot require'em. It's a bit frustrating.

In brief, I don't know how to clean importing the dependencies. Any idea? 

P.S: I've checked and re-checked your docs. Which are really fantastics but too shorts. We can also work towards enlarge them.

**Comment by edravis** [comment]
:( @jenius

**Comment by jenius** [comment]
Hi @edravis -- I'm currently working on a very limited basis and have little time to get to support requests. I'm really sorry, I feel bad and have a lot of people to get back to. I am doing my absolute best right now, and as soon as I have a moment I will take a look at this.

In the meantime, try http://gitter.im/jenius/roots -- you might be able to find some help there!

**Comment by edravis** [comment]
I understand. Don't worry I just wanted to confirm that you're busy. I'll try find some help in the gitter as you've pointed. Thank you anyway.

**Comment by jenius** [comment]
Hey there @edravis! I have a bit of time right now so let me try to address your questions here.

For browserify, that's fine! I usually use browserify in exactly this way and it works great.

As far as stylus goes, loading using `@import` works perfectly as far as I know. This is the primary way I load in stylus pieces, and I use it in all projects. In fact, just used it like 30 minutes ago. It might be an error in your stylus syntax. If you can create an isolated example of this I might be able to take a look!

For the last question, I'm afraid I don't understand exactly what you're asking. If you are using browserify, it will auto-ignore your starting point file. For css, you should prefix any files you are `@import` ing with an underscore to ensure they are ignored by the compiler.

Questions like this are much better asked in the gitter room though, since it's more of a request for help than an issue with roots! In addition, there are more people than just me there and willing to help so you'd get a quicker answer, whereas not everyone is on top of handling issues in the repo as much. I'm going to close out this issue, but happy to continue discussion here when I am able.
