### ISSUE TITLE
Compiler doesn't create the proper directories

### ISSUE THREAD

**Issue by edravis** [jenius/roots#668]
I have the following `app.coffee`:

```coffeescript
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
browserify   = require 'roots-browserify'
css_pipeline = require 'css-pipeline'


module.exports =
  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf', '.bin', 'blog/**/*']

  extensions: [
    browserify
      files: 'assets/scripts/main.js'
      out: 'js/build.js'
      minify: false
    css_pipeline
      files: [
        'assets/styles/vendor/*.*',
        'assets/styles/master.styl'
      ]
      out: 'css/bundle.css'
      minify: false
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: false

  'coffee-script':
    sourcemap: true

  jade:
    pretty: true
```

And after the compile it doesn't create the `js/` directory inside `public/`. Oddly, it creates perfectly the `css/` and `img/`.

Weird behaviour. At this moment I'm just compiling, then creating manually the directory and finally executing again the compiler. But doesn't look nor stable nor like a long-term solution.

Any suggestion?

**Comment by jenius** [comment]
Hey @edravis -- this is a question you might want to ask in the gitter chatroom. I don't have the capacity to debug personal roots projects at the moment. It would be amazing if you'd ask in the chatroom and if you think you have run into a bug, come back here with a very specific issue, rather than one that requires that I replicate your project and try to debug myself.

I'm sorry for having to give a response like this -- if I had more time I would definitely be able to spend more helping. But unfortunately for the next couple of months my time is capped pretty strongly so I have to be very careful splitting it up between things I need to work on!
