### ISSUE TITLE
After few recompiles it totally breaks

### ISSUE THREAD

**Issue by edravis** [jenius/roots#674]
I'm not sure how to reproduce it. But when I install it and I compile for the first time works fine. Then after multiple recompiles (compiling or by watching) it never ends to compile. Just stay on `compiling...` for ever.

A `--verbose` option would be much appreciate for these cases. Right now I cannot pass you any additional information.

At this moment the only solution that I've found is uninstall the full project and then clone and install it all again. Which is really frustrating.

Any idea or suggestion?

OFFTOPIC: Also, excuse me for the question, but is Roots ready for production? I'm starting to think that cannot work properly with the requirements of a production environment. Nor has stability enough. Roots really likes me but there are a lot of bugs around basic features. 

I try to help as much as I can but it's really hard without core maintainers. This is just my opinion and feels. I can be wrong, just wanted to share with you my thoughts.

**Comment by Leeds-eBooks** [comment]
Are you on version 3.2? If so, try rolling back to 3.1.0 and you should see the problem go away.

I've been using roots for a few weeks now and I would say that it absolutely is ready for production (well, 3.1.0 is!). For some of the more complex things like i18n, it's immature compared with other solutions like Middleman or DocPad. But the benefits (written in JavaScript, the multipass compilation using Accord, the extensibility, the `roots-records` extension) outweigh this in my opinion. I have spent a fair amount of time working on roots extensions rather than specifically on my website code over the past few weeks – if you don't have that luxury, you may want to look elsewhere. But there are many things I like about this library and I feel like it has a solid future. Especially if people like you and me and other users of roots can get involved in its maintenance.

**Comment by edravis** [comment]
@Leeds-eBooks thanks for take the time on this reply. I already have the 3.1.0 because another trouble that I had. Also, I've tried right now to reinstall the whole roots from `npm global` and still broke.
Do you think my version of node could affect? Which one is the more stable? I currently working over 2.0.0.

About the other topic, I agree with you in the feeling about the future of Roots. That's because we jump into this framework and not Harp which was the other option in the final round. But I still thinking that lacks of some core contributors. But, of course, this is my humble opinion. As a single developer what I can promise is that when I have enough time I'll PR some bugs that I've found; alike some devflow improvements.

**Comment by edravis** [comment]
I've found the trouble. Isn't roots breaking completely. It is that if I have any kind of mistake in the Javascript roots doesn't output me the error logs. It just stay compiling for eternity. Weird.

**Comment by Leeds-eBooks** [comment]
Interesting. What JS extensions are you using?

**Comment by edravis** [comment]
`roots-browserify` for the compiler
Inside the app mainly: `react` and `superagent`

**Comment by Leeds-eBooks** [comment]
I am using `webpack` with a `babel` loader, which logs JS syntax errors on compile. Maybe you can use a js lint extension or lint using browserify somehow.

**Comment by edravis** [comment]
Tomorrow is holidays at my city. I'll check the internal pipe compiler of `roots`. It has worked before so somewhat something has broken. I'll figure how to fix it. Really thankful for you help @Leeds-eBooks I'll let this issue opened waiting for the PR

**Comment by edravis** [comment]
I've issolated the problem on `roots-browserify`

We're moving here: https://github.com/carrot/roots-browserify/issues/26
