### ISSUE TITLE
Trouble with less

### ISSUE THREAD

**Issue by pauljakobwhite** [jenius/roots#691]
Hello I am trying to exchange stylus for less, or anything else really. I'm just trying to see what will be the best environment for us. But I seem to be having trouble configuring roots appropriately to use less. We don't need axis or rupture, but would like to keep autoprefixer. Does anyone know how we can achieve this in app.coffee?

We have checked out the docs for less on the accord repo but it seems we are still missing something key, running roots watch just throws an error.

**Comment by declandewet** [comment]
Hi @pauljakobwhite 

In order to get LESS working, you'll need to do a few things.

# Installing

First up, since Accord doesn't provide it's own version of the engine, you'll need to install LESS in your Roots project:

```
$ npm i less -s
```

Accord, in the context of a Roots project, will then automatically have access to the LESS compiler.

# Configuring Less

The next step is to configure Less in your `app.coffee`. Since Accord only supports  the `sourceMap` option for Less, your configuration might look like this:

*app.coffee*
```coffee
module.exports =
  ...
  less:
    sourceMap: true
```

# Getting Less to compile your stylesheets

Following the previous changes, there is one extra step needed to get Less to work. Navigate to `assets/css` and change the file extension of all stylesheet assets from `styl` to `less`. This allows Accord to detect and compile the files. So, your `assets/css` directory would look like this:

```
assets/
  css/
    master.less
```

The final step for triggering compiles is to convert the syntax of `master.less` from Stylus to Less.

# Adding `autoprefixer`

Since Roots does not expose an Accord engine's raw methods, and takes only options passed directly to the engine, you can't use Less' `render` method to transform the CSS once it is compiled.

But you can still enable `autoprefixer` in a number of ways:

1. Use the [`after` hook in `app.coffee`](http://roots.cx/docs/configuration#after) to detect CSS files and run them through `autoprefixer` directly
2. Extract the above into a [Roots Extension](http://roots.cx/docs/extensions)
3. Make use of [Multipass Compilation](http://roots.cx/docs/multipass)

Option 3 is the easiest and most preferred method for something as trivial as running `autoprefixer`, as Accord already supports `postcss` so that's the method I will focus on.

## Installing `autoprefixer`

This is easy. You'll need to install and configure `postcss` and `autoprefixer`:

```
npm i postcss autoprefixer -s
```

`autoprefixer` is a `postcss` plugin at its core, so `postcss` is the `accord` engine you'll use to add `autoprefixer`.

## Enabling Multipass Compilation

Assuming your `master.less` imports all of your CSS files, just change the file extension of your `master.less` to `master.css.less`. In order from right to left, Accord will map the extension of the file and run the appropriate engine compiler for the extension. In this case, it will attempt to run Less, followed by `postcss`.

If you have multiple top-level stylesheets, they too should have the extension `.css.less`.

Now all you need to do is add the `postcss` configuration to your `app.coffee`:

```coffee
autoprefixer = require 'autoprefixer'

module.exports =
  ...
  less:
    sourceMap: true
  postcss:
    use: [autoprefixer()]
```

That should kick things into gear.

# [optional] Scaffolding

Roots' CLI offers a `tpl` or `template` [option](http://roots.cx/docs/cli#template) that wraps [Sprout](/carrot/sprout), a lightweight project scaffolding tool similar to [Yeoman](/yeoman/yeoman).

Using Sprout, you can create a base template that does all of this for you automatically. Follow the instructions over at Sprout's readme. Root's [base template](https://github.com/carrot/base) (the one `roots new` uses by default) is a good example resource.

Put your new Sprout template up on Github, and then add it to Roots (I'll name it "la" for brevity):

```
$ roots tpl add la git@github.com:pauljakobwhite/la.git
```

Now you can do this to initialize a new Roots project with Less and Autoprefixer:

```
$ roots new -t la
```

If you want to make your template the default when running `$ roots new`, then run this command:

```
$ roots tpl default la
```

**Comment by pauljakobwhite** [comment]
This is incredible, thank you!

**Comment by jenius** [comment]
Nailed it, thanks @declandewet :grinning:
