### ISSUE TITLE
Instructions on how to debug extenstions [request]

### ISSUE THREAD

**Issue by orenmizr** [jenius/roots#696]
i know how to debug scripts. having trouble to debug with the roots command in the middle. 

 using webstorm and/or iron-node. 

would appreciate assistance.

**Comment by jenius** [comment]
Need a lot more info here to be able to figure out what your issue is and how we can help with solving it...

**Comment by orenmizr** [comment]
platforms: windows 10

i have been using some the extensions - some of them are failing for different reasons. roots-colllection had mac only path for example. 

i want to be able to run roots in debug mode - having the ability to break in some the extension and figure out what is wrong. 

I can't seem to do it since i am not running "node script.js" but a "root watch" command. 

when trying to setup webstorm debug node engine or iron-node to run roots - it fails on syntax. i am sure there is an easy way to setup. not sure what it is.

**Comment by jenius** [comment]
I'm sorry, I don't really know what webstorm or iron-node are, and unfortunately I can't develop roots around these specific tools. Roots exposes a command line interface and a javascript API, and that's all I plan on having it expose.

However, if you'd like to debug an extension, you can quite easily get inside of one of them. Just go into your `node_modules` folder then navigate to the folder for that extension. From there, you can check out the code and add `console.log`s wherever you want and figure out this issue. Another good approach is to file an issue in the extension's repo and ask the author about the issue you are having. You can find roots-collections' repo [here](https://github.com/netlify/roots-collections).

Hope you can figure this out, and happy to help if you have any further questions!

**Comment by orenmizr** [comment]
i have been using console logs and i have been in contact with authors of extension. that is still being half blind. 

i figured since you are the main developer you have a good setup. nevermind.

**Comment by jenius** [comment]
Sorry that you feel that way @orenmizr! I'm afraid it's hard for me to imagine how directly interacting with the code that's being executed can be interpreted as "half blind", but alas I may simply be ignorant to the nature of your apparently superior tooling.

Keep in mind that this is an open source project, and as is the case with all interaction with any open source projects, the most important thing is to make sure you are here with a spirit of openness, politeness, and willingness to learn and contribute.

If there's other questions I can answer or anything else I can help with I will be here, using my free time to try to make your life easier :grinning:

**Comment by jenius** [comment]
Hey also I had a moment to take a look at iron-node. It says you can just point it to a node.js file and it will do its thing. Roots is written in node.js entirely, so it seems feasible that you'd be able to get it to work.

When you run `roots watch`, this is simply a command line abbreviation for a script execution, in this case it's a [node script](https://github.com/jenius/roots/blob/master/bin/roots). So in theory if you can find out where that script is, you can run `iron-node` on that script and it will work the way you intend.

In unix, you can use `which roots` to reveal the location of the bin's alias. Typically it will be in `/usr/local/bin/roots`. On windows, I don't know because I never use windows, but I'm sure you could figure this out. Have you given this a try?

Please note that this issue has nothing to do with roots at all, and is just trying to get around a personal issue for you with your setup, which is why I closed it originally. But in the spirit of trying to be helpful, perhaps this will get you moving in the right direction.

**Comment by orenmizr** [comment]
i absolutely did not mean to offend, honestly. you've build something that is beautifully balanced between flexibility and simplicity. the fact you say you did it without the ability to pause execution and debug is admirable. I assumed that wasn't the case since you've written most of the code, hence my question. 

i personally need a debug tool. i feel it makes me personally more productive. but that is subjective.  

btw.
i did try directing iron-node and intelij to what i thought were the files. but it did not work for me. i do know it is not a roots question per-say :) hashtag shotinthedark

thanks.

**Comment by jenius** [comment]
Where were the files you were looking for? It should be just one file. Did you `cat` the file and see if it actually was the correct bin file? Is there a way to pass a standard command line argument along with `iron-node`? You'd need to call the file and also pass in the `watch` argument. I feel like you could figure this one out, you must be pretty close already.

Truth is that you get the same snapshot effect of stopping execution by just logging out the relevant values and letting execution complete, and/or thoroughly reading the error trace. If I am unable to figure out the issue through the error trace and maybe a console log or two, for me this usually means that there's something about the architecture or the language that I don't understand. You'll find that most javascript developers do not use IDEs or complex debugging tools, but still manage to be productive and write good code. And there's the additional benefit of not needing as many tools or depending on as many things in order to work, which is really nice, hashtag minimalism :wink:
